### ISSUE TITLE
Timeout on Travis CI

### ISSUE THREAD

**Issue by halfzebra** [elm-community/elm-test#182]
I'm getting a timeout from Travis CI.

Here are my `.travis.yml`:

```yml
language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
    - elm-stuff/build-artifacts
    - elm-stuff/packages
```

And the `package.json`:

```json
{
  "devDependencies": {
    "elm": "^0.18.0",
    "elm-test": "^0.18.6"
  },
  "scripts": {
    "postinstall": "elm-package install -y",
    "test": "elm-test"
  }
}
```

The output I'm getting from Travis CI:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

Here's the [log](https://travis-ci.org/halfzebra/elm-aframe/builds/248478108?utm_source=github_status&utm_medium=notification) and the entire [Pull request.](https://github.com/halfzebra/elm-aframe/pull/22/files) 😕 

What am I doing wrong? Is this a bug?
